---
title: "Replication"
author: "Robert Feldstein, Melissa Eckert, Yue Li, Kanna Chen"
date: "2025-02-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(openxlsx)

```

Load in the dataset
```{r}
# Open the dataset
df <- read.xlsx("../Data/FinalDataSet.xlsx")
```

## Entrustment Score Distribution

```{r}

score_columns <- colnames(df)[4:16]
# Store all of the scores in a single vector
all_scores <- c(rep(NA, length(score_columns)))
for (i in 1:length(score_columns)) {
  all_scores <- c(all_scores, df[[score_columns[i]]])
}

# Remove NA values 
all_scores <- all_scores[!is.na(all_scores)]

mean_score <- mean(all_scores)

# Add the mean of the score as text to the plot
ggplot(data = data.frame(score = all_scores), aes(x = score)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black") +
  labs(title = "Distribution of Entrustment Scores",
       x = "Entrustment Score",
       y = "Frequency") +
  theme_minimal() +
  geom_vline(xintercept = mean_score, color = "blue") +
  annotate("text", x = 1, y = 7000, label = paste("Mean Score: ", round(mean_score, 2))) +
  annotate("text", x = 1.5, y = 6000, label = paste("Total Observations: ", length(all_scores)))




```

```{r}
# Test linear regression
sample_df <- df[,c("strBlock", "medical", "clinical_reasoning", "professionalism", "collaboration", "patient_care", "Average", "procedural", "oral", "written")]

# Categorical Model
cat.fit <- lm(medical ~ strBlock, data = sample_df)


# Linear Model
# Convert strBlock to numeric 

labels <- c("A1", "A2", "A3", "A4", "A5", "A6", "A7", "B1", "B2", "B3", "B4", 
            "B5", "B6", "C1", "C2", "C3", "C4", "C5", "C6", "D1","D2", 
            "D3", "D4", "D5", "D6")

# Create a mapping of labels to integers
label_mapping <- setNames(1:length(labels), labels)

# Convert strBlock column to integers
sample_df$strBlockint<- label_mapping[sample_df$strBlock]


# Make medical linear regression
lm.fit.medical <- lm(medical ~ strBlockint, data = sample_df)


# Make clinical reasoning linear regression
lm.fit.clinical_reasoning <- lm(clinical_reasoning ~ strBlockint, data = sample_df)


# Make professionalism linear regression
lm.fit.professionalism <- lm(professionalism ~ strBlockint, data = sample_df)


# Make collaboration linear regression
lm.fit.collaboration <- lm(collaboration ~ strBlockint, data = sample_df)


# Make patient care linear regression
lm.fit.patient_care <- lm(patient_care ~ strBlockint, data = sample_df)


# Procedural
lm.fit.procedural <- lm(procedural ~ strBlockint, data = sample_df)

# Oral

lm.fit.oral <- lm(oral ~ strBlockint, data = sample_df)

# Written

lm.fit.written <- lm(written ~ strBlockint, data = sample_df)

# Overall

lm.fit.average <- lm(Average ~ strBlockint, data = sample_df)


```

```{r}
# Get the 25th percentile and 10th percentile of each of the scores

# Manipulating Time

columns <- c("Average", "medical", "clinical_reasoning",  "patient_care", "procedural", "oral", "written")
percentiles <- c(0.25, 0.10)
nmat <- matrix(NA, nrow = length(columns), ncol = length(percentiles))

for (i in 1:length(columns)) {
  for (j in 1:length(percentiles)) {
    nmat[i, j] <- quantile(df[[columns[i]]], probs = percentiles[j], na.rm=T)
  }
}

rownames(nmat) <- columns
colnames(nmat) <- paste0(percentiles * 100, "%")
nmat


```

```{r}

# Make a function that computes these confidence intervals a bunch of times

compute_time <- function(target_score, lm.fit) {
  beta_0 <- coef(lm.fit)[1]  # Intercept
  beta_1 <- coef(lm.fit)[2]  # Slope
  
  # Compute the estimated time
  estimated_time <- (target_score - beta_0) / beta_1
  se_beta <- summary(lm.fit)$coefficients[, 2]
  
  # Approximate standard error of estimated time using propagation formula
  se_time <- sqrt((se_beta[1] / beta_1)^2 + (se_beta[2] * (target_score - beta_0) / beta_1^2)^2)
  
  # Compute 95% confidence interval
  time_lwr <- estimated_time - 1.96 * se_time
  time_upr <- estimated_time + 1.96 * se_time
  
  return(c(estimated_time, time_lwr, time_upr,beta_1))
}

regression_models <- list(lm.fit.average, lm.fit.medical,
  lm.fit.clinical_reasoning, lm.fit.patient_care, lm.fit.procedural, lm.fit.oral, lm.fit.written)

times <- matrix(NA, nrow = length(regression_models), ncol = 4)

for (i in 1:length(regression_models)) {
  times[i, ] <- compute_time(4, regression_models[[i]])
}

# Rename the rows and columns
rownames(times) <- c("Average", "Medical", "Clinical Reasoning", "Patient Care", "Procedural", "Oral", "Written")
colnames(times) <- c("Estimated Time", "Lower Bound", "Upper Bound", "Slope")
times


```



## Comparison of Entrustment Scores between Student Employees & Student Non-employees
```{r}
#simple linear regression
df2<- df |>
  select(strBlock, Hosp, Average) |>
  mutate(Hosp = factor(Hosp, labels = c("No Hospital Job", "Hospital Job")))

labels <- c("A1", "A2", "A3", "A4", "A5", "A6", "A7", "B1", "B2", "B3", "B4", 
            "B5", "B6", "C1", "C2", "C3", "C4", "C5", "C6", "D1","D2", 
            "D3", "D4", "D5", "D6")

# create a mapping of labels to integers
label_mapping <- setNames(1:length(labels), labels)

# convert strBlock column to integers
df2$strBlockint<- label_mapping[df2$strBlock]

#Without considering strBlock as a predictor
fit<- lm(Average ~ Hosp, data = df2)
summary(fit)

#Considering strBlock as a predictor
fit2<- lm(Average ~ Hosp + strBlockint, data = df2)


#strBlock * Hosp interaction term
fit3<- lm(Average ~ Hosp * strBlockint, data = df2)


df2 |>
  group_by(strBlock, Hosp) |>
  summarize(hosp_entrustment_score = mean(Average))|>
ggplot(aes(x = strBlock, y = hosp_entrustment_score, color = Hosp)) + 
  geom_point() +
  geom_smooth(method = "lm",se = FALSE, aes(group = Hosp)) +
  scale_y_continuous(limits = c(1,5) ) +
  scale_color_manual(values = c("red", "blue")) +
  labs(title = "Comparison of Entrustment Scores Between Student Employees 
       & Student Non-Employees", x = "Rotation Block",
       y = "Entrustment Score", color = "Mean by Rotation") + 
  theme_minimal()
```
```{r}
#t-test to compare means between the two groups 
t.test(Average ~ Hosp, data = df2, var.equal = FALSE )

#highly significant!
```


## Comparison of Entrustment Scores Between Students Who Compeleted Introductory Rotation Courses vs Those Who Didn't
```{r}
#simple linear regression
df3<- df |>
  select(strBlock, Early, Average) |>
  mutate(Early = factor(Early, labels = c("No Introductory Course", "Introductory Rotation Course")))

labels <- c("A1", "A2", "A3", "A4", "A5", "A6", "A7", "B1", "B2", "B3", "B4", 
            "B5", "B6", "C1", "C2", "C3", "C4", "C5", "C6", "D1","D2", 
            "D3", "D4", "D5", "D6")

# create a mapping of labels to integers
label_mapping <- setNames(1:length(labels), labels)

# convert strBlock column to integers
df3$strBlockint<- label_mapping[df3$strBlock]

#Without considering strBlock as a predictor
fit<- lm(Average ~ Early, data = df3)
summary(fit)

#Considering strBlock as a predictor
fit2<- lm(Average ~ Early + strBlockint, data = df3)


#strBlock * Hosp interaction term
fit3<- lm(Average ~ Early * strBlockint, data = df3)


df3 |>
  group_by(strBlock, Early) |>
  summarize(early_entrustment_score = mean(Average))|>
ggplot(aes(x = strBlock, y = early_entrustment_score, color = Early)) + 
  geom_point() +
  geom_smooth(method = "lm",se = FALSE, aes(group = Early)) +
  scale_y_continuous(limits = c(1,5) ) +
  scale_color_manual(values = c("red", "blue")) + 
    labs(title = "Comparison of Entrustment Scores Between Students Who
       Completed Introductory Rotations vs Those Who Did Not", x = "Rotation Block",
       y = "Entrustment Score", color = "Mean by Rotation") +
  theme_minimal()
```
```{r}
#t-test to compare means between the two groups 
t.test(Average ~ Early, data = df3, var.equal = FALSE )

#no significant difference
```
